version: '3.3'

services:
  app:
    image: andrykar/mptapi:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8085:21000
    tty: true
    depends_on:
      - cache
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-stack-server