version: '3.3'

services:
  app:
    image: andrykar/mptapi:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8085:21000
    volumes:
      - ./MptApi:/usr/src/app
    tty: true
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A MptApi worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - app
  celery-beat:
    build: .
    command: celery -A MptApi beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - app
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-stack-server